name: ruby_task

services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      MYSQL_ROOT_PASSWORD: root
      REDIS_URL: redis://redis:6379/1
      ELASTICSEARCH_URL: http://elastic:root@elasticsearch:9200
    ports:
      - 3000:3000
    volumes:
      - ../.:/home/vscode/workspace
    depends_on:
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
      db:
        condition: service_healthy
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin --password=root ping --silent" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      ELASTIC_PASSWORD: root
    mem_limit: 1GB
    ports:
      - 9200:9200

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

volumes:
  db_data:
