---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/applications":
    post:
      summary: create application
      responses:
        '200':
          description: successful
  "/applications/{token}":
    parameters:
    - name: token
      in: path
      description: token
      required: true
      schema:
        type: string
    get:
      summary: show application
      responses:
        '200':
          description: successful
    patch:
      summary: update application
      responses:
        '200':
          description: successful
    put:
      summary: update application
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
