name: ruby_task

services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      CHATS_DATABASE_PASSWORD: admin
      DB_HOST: db
    command: tail -f /dev/null

    volumes:
      - ../.:/home/vscode/workspace
    depends_on:
      - db
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ruby_task
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
