name: ruby_task

services:
  app:
    build:
      dockerfile: Dockerfile
    command: tail -f /dev/null
    environment:
      CHATS_DATABASE_PASSWORD: admin
      DB_HOST: db
      REDIS_URL: redis://redis:6379/1
      ELASTICSEARCH_URL: http://elastic:root@elasticsearch:9200
    volumes:
      - ../.:/home/vscode/workspace
    depends_on:
      - db
      - elasticsearch
      - redis
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
      ELASTIC_PASSWORD: root
    mem_limit: 1GB
    ports:
      - 9200:9200

  redis:
    image: redis:6.2
    ports:
      - 6379:6379


volumes:
  db_data:
